### ISSUE TITLE
Exception while closing the DHT

### ISSUE THREAD

**Issue by manaty** [the8472/mldht#14]
When closing the dht, using [Bt java torrent library](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/bt-dht/src/main/java/bt/dht/MldhtService.java), i encounter the following exception:

java.nio.file.AccessDeniedException: C:\Users\smichea\AppData\Local\Temp\unlink-test5833109488279068966.tmp
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
        at java.nio.file.Files.delete(Unknown Source)
        at the8472.utils.AnonAllocator.<clinit>(AnonAllocator.java:30)
        at lbms.plugins.mldht.kad.Node.saveTable(Node.java:885)
        at lbms.plugins.mldht.kad.DHT.stop(DHT.java:869)
        at bt.dht.MldhtService.shutdown(MldhtService.java:144)

**Comment by the8472** [comment]
It's actually just superfluous debug information, I will remove the output.
