### ISSUE TITLE
NPE on closedown

### ISSUE THREAD

**Issue by parg** [the8472/mldht#17]
Getting a shed-load of when closing down

 java.lang.NullPointerException
	at lbms.plugins.mldht.kad.DHT$2.stateTransition(DHT.java:639)
	at lbms.plugins.mldht.kad.RPCCall.stateTransition(RPCCall.java:218)
	at lbms.plugins.mldht.kad.RPCCall.checkStallOrTimeout(RPCCall.java:172)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at the8472.utils.concurrent.NonblockingScheduledExecutor$SchedF.run(NonblockingScheduledExecutor.java:296)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by the8472** [comment]
should be fixed with b6467a803b
