### ISSUE TITLE
Getting error building/running

### ISSUE THREAD

**Issue by 7--** [the8472/mldht#31]
git clone https://github.com/the8472/mldht.git 
cd mldht
mvn package dependency:copy-dependencies appassembler:assemble

#Get error here
mvn antrun:run@link
```
[[1;34mINFO[m] Error stacktraces are turned on.
[[1;34mINFO[m] Scanning for projects...
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m------------------------< [0;36mmldht.core:libmldht[0;1m >-------------------------[m
[[1;34mINFO[m] [1mBuilding mldht - Bittorrent Mainline DHT library 0.1.1-SNAPSHOT[m
[[1;34mINFO[m] [1m--------------------------------[ jar ]---------------------------------[m
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-antrun-plugin:1.8:run[m [1m(link)[m @ [36mlibmldht[0;1m ---[m
[[1;33mWARNING[m] Parameter tasks is deprecated, use target instead
[[1;34mINFO[m] Executing tasks

main:
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  0.706 s
[[1;34mINFO[m] Finished at: 2021-08-25T16:17:35-04:00
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-antrun-plugin:1.8:run[m [1m(link)[m on project [36mlibmldht[m: [1;31mAn Ant BuildException has occured: ln failed with return code 1[m
[[1;31mERROR[m] [1;31maround Ant part ...<symlink resource="/home/phil/eclipse-workspace/mldht/bin/mldht-daemon" link="/home/phil/bin/mldht-daemon"/>... @ 4:111 in /home/phil/eclipse-workspace/mldht/target/antrun/build-main.xml[m
[[1;31mERROR[m] -> [1m[Help 1][m
[1;31morg.apache.maven.lifecycle.LifecycleExecutionException[m: [1;31mFailed to execute goal [32morg.apache.maven.plugins:maven-antrun-plugin:1.8:run[m [1m(link)[m on project [36mlibmldht[m: [1;31mAn Ant BuildException has occured: ln failed with return code 1
around Ant part ...<symlink resource="/home/phil/eclipse-workspace/mldht/bin/mldht-daemon" link="/home/phil/bin/mldht-daemon"/>... @ 4:111 in /home/phil/eclipse-workspace/mldht/target/antrun/build-main.xml[m[m
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:215[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:957[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:289[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:193[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
[1mCaused by[m: org.apache.maven.plugin.MojoExecutionException: [1;31mAn Ant BuildException has occured: ln failed with return code 1
around Ant part ...<symlink resource="/home/phil/eclipse-workspace/mldht/bin/mldht-daemon" link="/home/phil/bin/mldht-daemon"/>... @ 4:111 in /home/phil/eclipse-workspace/mldht/target/antrun/build-main.xml[m
    [1mat[m org.apache.maven.plugin.antrun.AntRunMojo.execute ([1mAntRunMojo.java:342[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:137[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:210[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:957[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:289[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:193[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
[1mCaused by[m: org.apache.tools.ant.BuildException: [1;31mln failed with return code 1[m
    [1mat[m org.apache.tools.ant.taskdefs.Execute.runCommand ([1mExecute.java:667[m)
    [1mat[m org.apache.tools.ant.taskdefs.optional.unix.Symlink.doLink ([1mSymlink.java:488[m)
    [1mat[m org.apache.tools.ant.taskdefs.optional.unix.Symlink.single ([1mSymlink.java:170[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.apache.tools.ant.dispatch.DispatchUtils.execute ([1mDispatchUtils.java:77[m)
    [1mat[m org.apache.tools.ant.Task.perform ([1mTask.java:348[m)
    [1mat[m org.apache.tools.ant.Target.execute ([1mTarget.java:435[m)
    [1mat[m org.apache.tools.ant.Target.performTasks ([1mTarget.java:456[m)
    [1mat[m org.apache.tools.ant.Project.executeSortedTargets ([1mProject.java:1393[m)
    [1mat[m org.apache.tools.ant.Project.executeTarget ([1mProject.java:1364[m)
    [1mat[m org.apache.maven.plugin.antrun.AntRunMojo.execute ([1mAntRunMojo.java:313[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:137[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:210[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:957[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:289[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:193[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
[[1;31mERROR[m] 
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```
If I try to run 
java -cp "../target/*:../target/dependency/*" the8472.mldht.Launcher
`
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:848)
	at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:219)
	at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
	at the8472.mldht.Launcher.start(Launcher.java:220)
	at the8472.mldht.Launcher.main(Launcher.java:303)

`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-81-generic", arch: "amd64", family: "unix"

**Comment by the8472** [comment]
> `mvn antrun:run@link`

This shouldn't be a critical failure, it just doesn't create a convenience symlink. I guess `~/bin` doesn't exist on your system?

> ` java.net.SocketException: Network is unreachable`

That exception in itself [is caught](https://github.com/the8472/mldht/blob/9ccb134ee312d8d85beb538eb8d6551e7fdb0292/src/lbms/plugins/mldht/kad/utils/AddressUtils.java#L213-L230) and not fatal but it indicates that your machine lacks IPv4 or IPv6 connectivity which likely causes problems afterwards. Did you follow the network [configuration steps](https://github.com/the8472/mldht#network-configuration)?

The default configuration is meant for server-class machines with public IPv4 and IPv6 addresses.
